package runtime

import "time"

//
// ──────────────────────────────── WORKFLOW & PLANNING ────────────────────────────────
//

// PlanStep defines a single planned operation in the workflow.
type PlanStep struct {
	Index  int    `json:"index"`
	Name   string `json:"name"`
	Intent string `json:"intent"`
}

// Plan is the sequence generated by the Planner agent.
type Plan struct {
	ID        string     `json:"id"`
	Steps     []PlanStep `json:"steps"`
	CreatedAt time.Time  `json:"createdAt"`
}
